version: '3.8'
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/app
    ports:
        - 8000:8000
    networks:
      - fluffy
  queue:
      build:
        context: .
        dockerfile: Dockerfile
      command: 'php artisan queue:work'
      depends_on:
        - db
      networks:
        - fluffy
  db:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER_ROOT=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=fluffy
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - fluffy

networks:
  fluffy:
    driver: bridge
